//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCvWpfTracking.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }

        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rtsp://root:rmffhqjf1!@192.168.1.2:554/AVStream1_1")]
        public string SavedEoRtspUrl {
            get { return ((string)(this["SavedEoRtspUrl"])); }
            set { this["SavedEoRtspUrl"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rtsp://root:rmffhqjf1!@192.168.0.121:554/cam0_0")]
        public string SavedIrRtspUrl {
            get { return ((string)(this["SavedIrRtspUrl"])); }
            set { this["SavedIrRtspUrl"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("옥상 GOP 주간(EO)")]
        public string SavedEoRtspPreset {
            get { return ((string)(this["SavedEoRtspPreset"])); }
            set { this["SavedEoRtspPreset"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("옥상 GOP 열상(IR)")]
        public string SavedIrRtspPreset {
            get { return ((string)(this["SavedIrRtspPreset"])); }
            set { this["SavedIrRtspPreset"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("옥상 GOP EO/IR - LA 방식")]
        public string SavedControlAgentProfile {
            get { return ((string)(this["SavedControlAgentProfile"])); }
            set { this["SavedControlAgentProfile"] = value; }
        }

    }

}
